#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prepare_commonkg.py

OAEI Common Knowledge Graphs track (class alignment across general-purpose KGs):
NELL -> DBpedia (129 gold correspondences) and YAGO/schema.org -> Wikidata (304).

A class is a bare symbol in its KG's own naming convention (NELL "academicfield",
DBpedia "AcademicSubject", schema.org "AccountingService", Wikidata
"accounting_services"), so its contexts are generated by Claude, grounded in a
deterministic sample of the class's instances from the track's own data. The
generator, the LEFT/RIGHT fragment protocol and the label insertion are shared
with Bio-ML (bioml/generate_bioml_contexts_claude.py); only the domain prompt
differs.

Output per test case is a context_run_dir that the Bio-ML hidden-state cache,
encoder and analyze_bioml_idf.py read unchanged:

    <output_dir>/<case>/selected_queries.json   one query per gold pair; the
                                               candidates are ALL target classes
    <output_dir>/<case>/contexts/{src,tgt}/*.json

The side of each RDF file is decided from the reference IRIs, not from the file
name (the NELL-DBpedia source.rdf holds DBpedia).

Example:
    python kg/prepare_commonkg.py --data_dir <commonkg> --output_dir <out> --workers 16
"""

import argparse
import hashlib
import json
import random
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "bioml"))
import generate_bioml_contexts_claude as G  # noqa: E402
from generate_bioml_contexts_bio8b_maxdiverse import (  # noqa: E402
    POSITION_PLANS, SYNTAX_STYLES, atomic_json_dump, complete_cache, entity_output_path)

RDF = "{http://www.w3.org/1999/02/22-rdf-syntax-ns#}"
RDFS = "{http://www.w3.org/2000/01/rdf-schema#}"
DECLARATIONS = {"http://www.w3.org/2002/07/owl#Class",
                "http://www.w3.org/2000/01/rdf-schema#Class"}
ALIGN = "{http://knowledgeweb.semanticweb.org/heterogeneity/alignment}"

CASES = {
    "nell_dbpedia": ("KG_GoldeStandard/SmallTestCase", {"src": "NELL", "tgt": "DBpedia"}),
    "yago_wikidata": ("YagoWikiData/smallYWtestCase", {"src": "YAGO (schema.org classes)",
                                                        "tgt": "Wikidata"}),
}

SYSTEM_PROMPT = """You are an expert in knowledge graphs, ontologies and general world knowledge.

Create highly diverse natural-language contexts for one CLASS (category) from a knowledge graph.

The SAME class name will appear in all contexts, so maximize everything else:
semantic content, surrounding vocabulary, grammar, clause structure, sentence rhythm,
perspective, and where the class name appears in the sentence.

Do not merely paraphrase the same definition. Use the supplied example instances and
your own knowledge of what the category means. Keep statements factually plausible.

You will NOT write the class name itself. Generate LEFT and RIGHT text fragments;
Python will insert the exact class name between them.

Return only valid JSON with no commentary."""

SEMANTIC_AXES = [
    "what the category is / its defining criterion",
    "typical members, drawing on the example instances",
    "characteristic attributes or properties its members share",
    "relations to broader and narrower categories",
    "where, when or in what domain members occur",
    "how members are used, produced, or interacted with",
    "contrast with a similar but different category",
    "how the category is named, catalogued or represented in data",
    "a concrete scenario involving a member of the category",
    "counting, classifying or recording members of the category",
]


def plans_for(meta, n):
    seed = int(hashlib.sha1(meta["entity_iri"].encode("utf-8")).hexdigest()[:8], 16)
    rng = random.Random(seed)
    axes, styles = SEMANTIC_AXES[:], SYNTAX_STYLES[:]
    rng.shuffle(axes)
    rng.shuffle(styles)
    return [{"slot": i + 1, "semantic_focus": axes[i % len(axes)],
             "syntax_style": styles[i % len(styles)],
             "position_name": POSITION_PLANS[i % 5][0],
             "target_symbol_fraction": POSITION_PLANS[i % 5][1],
             "position_instruction": POSITION_PLANS[i % 5][2]} for i in range(n)]


def build_prompt(meta, n):
    shown = {k: meta[k] for k in ("knowledge_graph", "class_name", "example_instances",
                                  "n_instances_in_kg")}
    return f"""CLASS METADATA:
{json.dumps(shown, ensure_ascii=False, indent=2)}

The class name is written exactly as "{meta['class_name']}" in this knowledge graph.

Generate exactly {n} MAXIMALLY DIVERSE contexts for this SAME class.

For each context, write:
- "left": text BEFORE the class name
- "right": text AFTER the class name

Python will construct:
LEFT + [EXACT CLASS NAME] + RIGHT

Do NOT include the class name itself in either fragment.

Vary content, vocabulary, grammar, voice, sentence length, framing and the position of
the class name. Do not reuse the same opening, linking phrase, main verb or template.

Follow these DIFFERENT plans independently:
{json.dumps(plans_for(meta, n), ensure_ascii=False, indent=2)}

POSITION RULE: approximate the requested position by controlling LEFT versus RIGHT
length (early: short LEFT; middle: similar; late: short RIGHT). Even for an early
position, put some meaningful material before the class name.

Return ONLY JSON in this exact form:
{{
  "contexts": [
    {{"left": "text before class name", "right": "text after class name"}}
  ]
}}

The contexts array must contain exactly {n} objects.
"""


def local_name(iri):
    s = iri.rstrip("/")
    for sep in ("pred:", "#", "/"):
        if sep in s:
            s = s.rsplit(sep, 1)[-1]
    return s


def parse_kg(path):
    """classes -> instance labels, from rdf:type edges (plus owl:Class declarations)."""
    members, labels = {}, {}
    declared = set()
    for d in ET.parse(path).getroot():
        about = d.attrib.get(RDF + "about")
        if not about:
            continue
        for c in d:
            if c.tag == RDFS + "label" and c.text:
                labels[about] = c.text
            elif c.tag == RDF + "type":
                t = c.attrib.get(RDF + "resource")
                if t in DECLARATIONS:
                    declared.add(about)
                elif t:
                    members.setdefault(t, []).append(about)
    classes = set(members) | declared
    return {c: sorted(labels.get(i, local_name(i)).replace("_", " ")
                      for i in members.get(c, [])) for c in classes}


def parse_reference(path):
    out = []
    for cell in ET.parse(path).getroot().iter(ALIGN + "Cell"):
        a = cell.find(ALIGN + "entity1").attrib[RDF + "resource"]
        b = cell.find(ALIGN + "entity2").attrib[RDF + "resource"]
        rel = (cell.findtext(ALIGN + "relation") or "=").strip()
        if rel == "=":
            out.append((a, b))
    return out


def prepare_case(name, root, kg_names, args):
    case_dir = root / CASES[name][0]
    refs = parse_reference(case_dir / "reference.rdf")
    kgs = [parse_kg(case_dir / "source.rdf"), parse_kg(case_dir / "target.rdf")]
    src_iris = {a for a, _ in refs}
    # The side whose classes cover the reference's entity1 is the source.
    cover = [len(src_iris & set(k)) for k in kgs]
    src_kg, tgt_kg = (kgs[0], kgs[1]) if cover[0] >= cover[1] else (kgs[1], kgs[0])
    for a, b in refs:
        src_kg.setdefault(a, [])
        tgt_kg.setdefault(b, [])
    targets = sorted(tgt_kg)
    queries = [{"query_id": i, "src": a, "gold": b, "candidates": targets}
               for i, (a, b) in enumerate(sorted(refs))]

    def meta(iri, kg, side):
        inst = kg[iri]
        rng = random.Random(int(hashlib.sha1(iri.encode()).hexdigest()[:8], 16))
        sample = rng.sample(inst, min(args.instances, len(inst)))
        return {"entity_iri": iri, "preferred_label": local_name(iri),
                "class_name": local_name(iri), "knowledge_graph": kg_names[side],
                "example_instances": sample, "n_instances_in_kg": len(inst)}

    out = args.output_dir / name
    jobs = ([{"side": "src", "iri": a, "meta": meta(a, src_kg, "src")}
             for a in sorted(src_iris)]
            + [{"side": "tgt", "iri": t, "meta": meta(t, tgt_kg, "tgt")} for t in targets])
    for j in jobs:
        j["path"] = entity_output_path(out, j["side"], j["iri"])
    atomic_json_dump(queries, out / "selected_queries.json")
    print(f"{name}: gold={len(refs)} src_classes={len(src_iris)} target_classes={len(targets)} "
          f"without instances: src {sum(not src_kg[a] for a in src_iris)}, "
          f"tgt {sum(not tgt_kg[t] for t in targets)}", flush=True)
    return jobs


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data_dir", type=Path, required=True,
                    help="dir holding the KG_GoldeStandard and YagoWikiData checkouts")
    ap.add_argument("--output_dir", type=Path, required=True)
    ap.add_argument("--cases", default="nell_dbpedia,yago_wikidata")
    ap.add_argument("--instances", type=int, default=20, help="example instances per class")
    G.add_api_args(ap)
    args = ap.parse_args()
    args.output_dir = args.output_dir.expanduser().resolve()

    jobs = []
    for name in [c for c in args.cases.split(",") if c]:
        jobs += prepare_case(name, args.data_dir.expanduser().resolve(), CASES[name][1], args)
    pending = [j for j in jobs if not complete_cache(j["path"], j["iri"], args.contexts)]
    print(f"entities={len(jobs)} pending={len(pending)} model={args.model} effort={args.effort}")

    tot, failures = G.generate_all(G.make_client(args), args, pending, system=SYSTEM_PROMPT,
                                   prompt_fn=build_prompt, plans_fn=plans_for)
    summary = {"entities": len(jobs), **tot, "model": args.model, "effort": args.effort,
               "failures": failures}
    atomic_json_dump(summary, args.output_dir / "generation_summary.json")
    print(json.dumps({k: v for k, v in summary.items() if k != "failures"}, indent=2))
    if failures:
        raise SystemExit(f"{len(failures)} entities failed; rerun to retry them")


if __name__ == "__main__":
    main()
