#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prepare_anatomy.py

OAEI Anatomy track: Adult Mouse Anatomy (MA, 2,744 classes) -> the NCI Thesaurus
anatomy fragment (3,304 classes), 1,516 gold equivalences.

Each class is given the same metadata fields as Bio-ML's ontology caches (preferred
label, synonyms, definitions, parent labels -- is-a and part-of), and its contexts
are generated by Claude with the Bio-ML max-diverse prompt unchanged, since this is
the same kind of biomedical ontology symbol. Labels are kept in each ontology's
own convention (MA "spinal cord grey matter", NCI "Anatomic_Structure_System_or_Substance").

Unlike Bio-ML's 100-candidate pools, every mouse class is ranked against ALL human
classes, so evaluate with analyze_bioml_idf.py --fast.

Output: <output_dir>/{selected_queries.json, contexts/{src,tgt}/*.json}, a
context_run_dir for the Bio-ML cache / encoder / analyzer.

Example:
    python ontology/prepare_anatomy.py --data_dir <anatomy> --output_dir <out> --workers 16
"""

import argparse
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "bioml"))
import generate_bioml_contexts_claude as G  # noqa: E402
from generate_bioml_contexts_bio8b_maxdiverse import (  # noqa: E402
    atomic_json_dump, complete_cache, entity_output_path)

RDF = "{http://www.w3.org/1999/02/22-rdf-syntax-ns#}"
RDFS = "{http://www.w3.org/2000/01/rdf-schema#}"
OWL = "{http://www.w3.org/2002/07/owl#}"
OBO = "{http://www.geneontology.org/formats/oboInOwl#}"
ALIGN = "{http://knowledgeweb.semanticweb.org/heterogeneity/alignment}"


def parse_ontology(path, name):
    root = ET.parse(path).getroot()
    labels = {}
    for d in root:
        about = d.attrib.get(RDF + "about")
        lab = d.find(RDFS + "label")
        if about and lab is not None and lab.text:
            labels[about] = lab.text.strip()
    meta = {}
    for c in root.iter(OWL + "Class"):
        iri = c.attrib.get(RDF + "about")
        if not iri or iri not in labels:
            continue
        refs = lambda tag: [labels[e.attrib[RDF + "resource"]] for e in c.findall(tag)
                            if e.attrib.get(RDF + "resource") in labels]
        parents = []
        for sc in c.findall(RDFS + "subClassOf"):
            r = sc.attrib.get(RDF + "resource")
            if r in labels:
                parents.append(labels[r])
            for v in sc.iter(OWL + "someValuesFrom"):  # part_of restrictions
                r = v.attrib.get(RDF + "resource")
                if r in labels:
                    parents.append(f"part of {labels[r]}")
        meta[iri] = {"entity_iri": iri, "ontology": name, "preferred_label": labels[iri],
                     "synonyms": sorted(set(refs(OBO + "hasRelatedSynonym")
                                            + refs(OBO + "hasExactSynonym"))),
                     "definitions": refs(OBO + "hasDefinition"),
                     "parent_labels": parents}
    return meta


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data_dir", type=Path, required=True,
                    help="holds source.rdf (mouse), target.rdf (human), reference.rdf")
    ap.add_argument("--output_dir", type=Path, required=True)
    G.add_api_args(ap)
    args = ap.parse_args()
    d, out = args.data_dir, args.output_dir.expanduser().resolve()

    mouse = parse_ontology(d / "source.rdf", "Adult Mouse Anatomy (MA)")
    human = parse_ontology(d / "target.rdf", "NCI Thesaurus anatomy")
    refs = []
    for cell in ET.parse(d / "reference.rdf").getroot().iter(ALIGN + "Cell"):
        a = cell.find(ALIGN + "entity1").attrib[RDF + "resource"]
        b = cell.find(ALIGN + "entity2").attrib[RDF + "resource"]
        if (cell.findtext(ALIGN + "relation") or "=").strip() == "=" and a in mouse and b in human:
            refs.append((a, b))
    targets = sorted(human)
    queries = [{"query_id": i, "src": a, "gold": b, "candidates": targets}
               for i, (a, b) in enumerate(sorted(refs))]
    atomic_json_dump(queries, out / "selected_queries.json")

    srcs = sorted({a for a, _ in refs})
    jobs = ([{"side": "src", "iri": a, "meta": mouse[a]} for a in srcs]
            + [{"side": "tgt", "iri": t, "meta": human[t]} for t in targets])
    for j in jobs:
        j["path"] = entity_output_path(out, j["side"], j["iri"])
    pending = [j for j in jobs if not complete_cache(j["path"], j["iri"], args.contexts)]
    print(f"mouse={len(mouse)} human={len(human)} gold={len(refs)} "
          f"entities={len(jobs)} pending={len(pending)}", flush=True)

    tot, failures = G.generate_all(G.make_client(args), args, pending)
    summary = {"entities": len(jobs), **tot, "model": args.model, "effort": args.effort,
               "protocol": "bio8b max-diverse prompt, generated by Claude",
               "failures": failures}
    atomic_json_dump(summary, out / "generation_summary.json")
    print(json.dumps({k: v for k, v in summary.items() if k != "failures"}, indent=2))
    if failures:
        raise SystemExit(f"{len(failures)} entities failed; rerun to retry them")


if __name__ == "__main__":
    main()
